'use client';

/**
 * AnalyticsDashboard — scan analytics + AI-generated insights.
 * Shows: total scans, unique QRs, 7-day trend, device breakdown, top QRs,
 * and natural-language insights generated by gpt-oss-120b.
 */
import { useEffect, useState } from 'react';
import {
  BarChart3, Smartphone, Globe, TrendingUp, Sparkles, Loader2,
  QrCode, MousePointerClick,
} from 'lucide-react';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell, Legend,
} from 'recharts';

interface AnalyticsData {
  totalScans: number;
  uniqueQrs: number;
  last7Days: { date: string; count: number }[];
  deviceBreakdown: { device: string; count: number }[];
  topQrs: {
    id: string; shortCode: string; label: string;
    category: string; scans: number; createdAt: string;
  }[];
}

interface AIInsight {
  title: string;
  detail: string;
  severity: 'positive' | 'neutral' | 'warning';
  recommendation: string;
}

const PIE_COLORS = ['#06b6d4', '#f59e0b', '#10b981', '#a855f7', '#ef4444'];

export function AnalyticsDashboard() {
  const [data, setData] = useState<AnalyticsData | null>(null);
  const [loading, setLoading] = useState(true);
  const [insights, setInsights] = useState<{
    insights: AIInsight[];
    summary: string;
  } | null>(null);
  const [insightLoading, setInsightLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const loadAnalytics = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/analytics');
      const d = await res.json();
      if (!res.ok) throw new Error(d.error || 'Failed to load');
      setData(d);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAnalytics();
  }, []);

  const generateInsights = async () => {
    if (!data) return;
    setInsightLoading(true);
    try {
      const res = await fetch('/api/ai/analytics-insights', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      });
      const d = await res.json();
      if (!res.ok) throw new Error(d.error || 'Failed');
      setInsights(d);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setInsightLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center text-slate-400">
        <Loader2 className="h-6 w-6 animate-spin" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="rounded-lg border border-red-500/40 bg-red-500/10 p-4 text-sm text-red-300">
        {error}
      </div>
    );
  }

  if (!data) return null;

  return (
    <div className="space-y-6">
      {/* KPI cards */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <StatCard
          icon={<MousePointerClick className="h-4 w-4" />}
          label="Total Scans"
          value={data.totalScans}
          color="cyan"
        />
        <StatCard
          icon={<QrCode className="h-4 w-4" />}
          label="Tracked QRs"
          value={data.uniqueQrs}
          color="violet"
        />
        <StatCard
          icon={<TrendingUp className="h-4 w-4" />}
          label="This Week"
          value={data.last7Days.reduce((a, b) => a + b.count, 0)}
          color="emerald"
        />
        <StatCard
          icon={<Globe className="h-4 w-4" />}
          label="Top Device"
          value={data.deviceBreakdown[0]?.device || '—'}
          color="amber"
        />
      </div>

      {/* 7-day trend */}
      <div className="rounded-xl border border-slate-800 bg-slate-900/40 p-4">
        <h3 className="mb-3 flex items-center gap-2 text-sm font-semibold text-slate-200">
          <BarChart3 className="h-4 w-4 text-cyan-400" />
          Scans · Last 7 Days
        </h3>
        {data.last7Days.every((d) => d.count === 0) ? (
          <div className="flex h-32 items-center justify-center text-sm text-slate-500">
            No scans yet this week.
          </div>
        ) : (
          <ResponsiveContainer width="100%" height={200}>
            <BarChart data={data.last7Days}>
              <XAxis
                dataKey="date"
                tick={{ fill: '#94a3b8', fontSize: 11 }}
                tickFormatter={(d) => d.slice(5)}
              />
              <YAxis tick={{ fill: '#94a3b8', fontSize: 11 }} allowDecimals={false} />
              <Tooltip
                contentStyle={{
                  background: '#0f172a',
                  border: '1px solid #1e293b',
                  borderRadius: '8px',
                  color: '#f1f5f9',
                }}
              />
              <Bar dataKey="count" fill="#06b6d4" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        )}
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        {/* Device breakdown */}
        <div className="rounded-xl border border-slate-800 bg-slate-900/40 p-4">
          <h3 className="mb-3 flex items-center gap-2 text-sm font-semibold text-slate-200">
            <Smartphone className="h-4 w-4 text-fuchsia-400" />
            Device Breakdown
          </h3>
          {data.deviceBreakdown.length === 0 ? (
            <div className="flex h-32 items-center justify-center text-sm text-slate-500">
              No data yet.
            </div>
          ) : (
            <ResponsiveContainer width="100%" height={200}>
              <PieChart>
                <Pie
                  data={data.deviceBreakdown}
                  dataKey="count"
                  nameKey="device"
                  cx="50%"
                  cy="50%"
                  outerRadius={70}
                  label={(entry) => `${entry.device} (${entry.count})`}
                  labelLine={false}
                >
                  {data.deviceBreakdown.map((_, i) => (
                    <Cell key={i} fill={PIE_COLORS[i % PIE_COLORS.length]} />
                  ))}
                </Pie>
                <Legend wrapperStyle={{ fontSize: 11 }} />
              </PieChart>
            </ResponsiveContainer>
          )}
        </div>

        {/* Top QRs */}
        <div className="rounded-xl border border-slate-800 bg-slate-900/40 p-4">
          <h3 className="mb-3 flex items-center gap-2 text-sm font-semibold text-slate-200">
            <QrCode className="h-4 w-4 text-emerald-400" />
            Top QR Codes
          </h3>
          {data.topQrs.length === 0 ? (
            <div className="flex h-32 items-center justify-center text-sm text-slate-500">
              No tracked QRs yet.
            </div>
          ) : (
            <ul className="space-y-2">
              {data.topQrs.slice(0, 5).map((q) => (
                <li
                  key={q.id}
                  className="flex items-center justify-between gap-2 rounded-md border border-slate-800 bg-slate-900/40 px-3 py-2"
                >
                  <div className="min-w-0 flex-1">
                    <div className="truncate text-xs font-medium text-slate-200">
                      {q.label}
                    </div>
                    <div className="text-[10px] uppercase tracking-wide text-slate-500">
                      {q.category}
                    </div>
                  </div>
                  <div className="text-sm font-semibold text-cyan-400">
                    {q.scans}
                  </div>
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>

      {/* AI Insights */}
      <div className="rounded-xl border border-fuchsia-500/30 bg-gradient-to-br from-fuchsia-500/10 to-cyan-400/5 p-4">
        <div className="mb-3 flex items-center justify-between">
          <h3 className="flex items-center gap-2 text-sm font-semibold text-slate-100">
            <Sparkles className="h-4 w-4 text-fuchsia-400" />
            AI Insights
          </h3>
          <button
            onClick={generateInsights}
            disabled={insightLoading || data.totalScans === 0}
            className="inline-flex items-center gap-1.5 rounded-md bg-fuchsia-500/20 px-2.5 py-1 text-xs font-medium text-fuchsia-200 hover:bg-fuchsia-500/30 disabled:opacity-40 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-fuchsia-400"
          >
            {insightLoading && <Loader2 className="h-3 w-3 animate-spin" />}
            {insights ? 'Regenerate' : 'Generate'}
          </button>
        </div>
        {data.totalScans === 0 ? (
          <p className="text-xs text-slate-400">
            Create a tracked QR and get some scans first — then I&apos;ll analyze the data for you.
          </p>
        ) : insights ? (
          <div className="space-y-3">
            <p className="text-xs text-slate-300">{insights.summary}</p>
            <ul className="space-y-2">
              {insights.insights.map((ins, i) => (
                <li
                  key={i}
                  className={`rounded-lg border-l-2 px-3 py-2 ${
                    ins.severity === 'positive'
                      ? 'border-emerald-400 bg-emerald-400/5'
                      : ins.severity === 'warning'
                        ? 'border-amber-400 bg-amber-400/5'
                        : 'border-slate-500 bg-slate-500/5'
                  }`}
                >
                  <div className="text-xs font-semibold text-slate-100">{ins.title}</div>
                  <div className="text-[11px] text-slate-300">{ins.detail}</div>
                  <div className="mt-1 text-[11px] italic text-slate-400">
                    → {ins.recommendation}
                  </div>
                </li>
              ))}
            </ul>
            <div className="text-[10px] text-slate-500">
              Powered by gpt-oss-120b on Groq.
            </div>
          </div>
        ) : (
          <p className="text-xs text-slate-400">
            Click <strong>Generate</strong> to get AI-generated insights from your scan data.
          </p>
        )}
      </div>
    </div>
  );
}

function StatCard({
  icon, label, value, color,
}: {
  icon: React.ReactNode;
  label: string;
  value: number | string;
  color: 'cyan' | 'violet' | 'emerald' | 'amber';
}) {
  const colors = {
    cyan: 'text-cyan-400 border-cyan-500/30 bg-cyan-500/5',
    violet: 'text-violet-400 border-violet-500/30 bg-violet-500/5',
    emerald: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/5',
    amber: 'text-amber-400 border-amber-500/30 bg-amber-500/5',
  };
  return (
    <div className={`rounded-xl border p-3 ${colors[color]}`}>
      <div className="flex items-center gap-1.5 text-xs font-medium opacity-80">
        {icon}
        {label}
      </div>
      <div className="mt-1 text-2xl font-bold">{value}</div>
    </div>
  );
}
